### ISSUE TITLE
收费有点贵啊需要购买的 一个月3k，一年2w

### ISSUE THREAD

**Issue by lishuanglong521** [netyouli/WHC_ConfuseSoftware#12]

**Comment by netyouli** [comment]
本人时刻关注苹果审核情况然后做调整，只是收点辛苦维护升级费用，同时收费另外一个目的只让部分用户使用限制使用门槛，如果免费使用（由于使用人太多了）用不了多久这个混淆效果就会失效。还请理解，谢谢

**Comment by q351941406** [comment]
要钱?散了散了,又不是多牛B的技术,收费比人工智能还贵.

**Comment by netyouli** [comment]
心情可以理解、但是没办法、还请见谅、谢谢
