### ISSUE TITLE
既然不想给用，有何必放github上

### ISSUE THREAD

**Issue by voisen** [netyouli/WHC_ConfuseSoftware#13]

**Comment by CoderMaurice** [comment]
的确，还写个 欢迎下载使用

**Comment by netyouli** [comment]
目前这软件具有特需性，不方便免费提供使用，否则会泛滥从而导致他人使用效果下降同时也是对现有vip会员的不公平行为，为了能够及时持续更新升级不断完善需要精力时间开发成本，所以需要购买vip才能使用，我之所以放在github上面主要为了方便下载，以及版本的更新方便，这软件注定是少数人才能使用的，网上也有很多处理混淆的开源免费的脚本和工具，根据自己的情况选择即可，还请谅解，谢谢。
